---
# install
- name: Enable zabbix repo.
  template: 
    src: zabbix.repo.j2
    dest: /etc/yum.repos.d/zabbix.repo

- name: Ensure zabbix utils are installed.
  yum: 
    name: "{{ item }}"
    enablerepo: epel
  with_items: [ iksemel, fping ]

- name: Ensure zabbix server is installed.
  yum:
    name: "{{ item }}"
    enablerepo: "{{ php_enablerepo }},{{ mysql_enablerepo }},zabbix"
  with_items:
    - zabbix-server-mysql
    - zabbix-web-mysql
    - zabbix-web-japanese

# database
- include: database.yml
  static: no
  when: "ansible_connection != 'docker'"
  
- name: Zabbix document root.
  file:
    path: /etc/zabbix/web
    owner: "{{ zabbix_server_web_user }}"
    group: "{{ zabbix_server_web_group }}"
    mode: 0755
    state: directory   
  changed_when: False

- name: Link to web root directory.
  file:
    src: /usr/share/zabbix
    dest: /var/www/zabbix
    owner: "{{ zabbix_server_web_user }}"
    group: "{{ zabbix_server_web_group }}"
    state: link

# configure
- name: Copy zabbix server configuration in place.
  template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: root
    group: root
    mode: 00640
  notify:
    - restart zabbix-server

- name: Copy zabbix php configuration in place.
  template:
    src: zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    owner: "{{ zabbix_server_web_user }}"
    group: "{{ zabbix_server_web_group }}"
    mode: 00640

# service
- name: Ensure zabbix-server is started and enabled to start at boot.
  service: name=zabbix-server state=started enabled=yes
  when: "ansible_connection != 'docker'"

# notify scripts
- name: Copy slack notification script in place.
  template:
    src: alart_slack.sh.j2
    dest: "{{ zabbix_server_AlertScriptsPath }}/slack.sh"
    mode: 0755

# clean
- name: Purge yum cache.
  command: yum clean all
  when: ansible_connection == 'docker'