---
# install
- name: Enable zabbix repo.
  template:
    src: zabbix.repo.j2
    dest: /etc/yum.repos.d/zabbix.repo
    owner: root
    group: root
    mode: 00644

- name: Ensure zabbix utils are installed.
  yum:
    name: "{{ item }}"
    state: installed
    enablerepo: epel
  with_items:
    - iksemel
    - fping

- name: Ensure zabbix server is installed.
  yum:
    name: "{{ item }}"
    state: installed
    enablerepo: "{{ php_enablerepo }},{{ mysql_enablerepo }},zabbix"
  with_items:
    - zabbix-server-mysql
    - zabbix-web-mysql
    - zabbix-web-japanese


# database
- name: Create a new database
  mysql_db: name={{ zabbix_server_db_name }} state=present

- name: Create database user and 'WITH GRANT OPTION'
  mysql_user:
    name: "{{ zabbix_server_db_user }}"
    password: "{{ zabbix_server_db_pass }}"
    priv: "{{ zabbix_server_db_name }}.*:ALL,GRANT"
    state: present

- name: Importing schema file
  shell: mysql -u {{ zabbix_server_db_user }} -p{{ zabbix_server_db_pass }} {{ zabbix_server_db_name }} -e "show tables;" | wc -l
  register: zabbix_database_tables
  changed_when: False
- shell: >
    zcat /usr/share/doc/zabbix-server-mysql-*/create.sql.gz |
      mysql -u{{ zabbix_server_db_user }} -p{{ zabbix_server_db_pass }} {{ zabbix_server_db_name }}
  when: zabbix_database_tables.stdout | int == 0

- name: Zabbix document root.
  file:
    path: /etc/zabbix/web
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: 00755
  changed_when: False

- name: Link to nginx directory.
  file:
    src: /usr/share/zabbix
    dest: /var/www/zabbix
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    state: link

# configure
- name: Copy zabbix server configuration in place.
  template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: root
    group: root
    mode: 00640
  notify:
    - restart zabbix-server

- name: Copy zabbix php configuration in place.
  template:
    src: zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: 00640

- name: Copy nginx configuration in place.
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/zabbix.conf
    owner: root
    group: root
    mode: 00644
  notify:
    - reload nginx

# service
- name: Ensure zabbix-server is started and enabled to start at boot.
  service: name=zabbix-server state=started enabled=yes
